name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Flutter analyze
      run: flutter analyze
    - name: Flutter test
      run: flutter test
    - name: Flutter build
      run: flutter build apk
