// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSEI2shCD9HaCEGZIOchBZG_mP12tedw',
    appId: '1:138749187378:android:65ade0ec1e5e908e86b32b',
    messagingSenderId: '138749187378',
    projectId: 'hustle-c1c70',
    storageBucket: 'hustle-c1c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA16P1VQay39VCrHUQBK6Uj9TPelUn23-E',
    appId: '1:138749187378:ios:75068b4400d2410c86b32b',
    messagingSenderId: '138749187378',
    projectId: 'hustle-c1c70',
    storageBucket: 'hustle-c1c70.appspot.com',
    androidClientId: '138749187378-qeco7ch1o8dl7edldprokk9qcstfd40i.apps.googleusercontent.com',
    iosClientId: '138749187378-7t4buaqsl6acp97uso977fd13k1hgdhl.apps.googleusercontent.com',
    iosBundleId: 'de.poxh.hustle',
  );
}
