// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQL6HUyJ_-8PCLQoDS7rMcObuZUZlhdzI',
    appId: '1:138749187378:web:badee34b2703261e86b32b',
    messagingSenderId: '138749187378',
    projectId: 'hustle-c1c70',
    authDomain: 'hustle-c1c70.firebaseapp.com',
    storageBucket: 'hustle-c1c70.appspot.com',
    measurementId: 'G-TD545DXTWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSEI2shCD9HaCEGZIOchBZG_mP12tedw',
    appId: '1:138749187378:android:dad296eb103cc7fe86b32b',
    messagingSenderId: '138749187378',
    projectId: 'hustle-c1c70',
    storageBucket: 'hustle-c1c70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA16P1VQay39VCrHUQBK6Uj9TPelUn23-E',
    appId: '1:138749187378:ios:735d92a3b1b0503786b32b',
    messagingSenderId: '138749187378',
    projectId: 'hustle-c1c70',
    storageBucket: 'hustle-c1c70.appspot.com',
    iosBundleId: 'com.example.hustle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA16P1VQay39VCrHUQBK6Uj9TPelUn23-E',
    appId: '1:138749187378:ios:e46c47474bec490986b32b',
    messagingSenderId: '138749187378',
    projectId: 'hustle-c1c70',
    storageBucket: 'hustle-c1c70.appspot.com',
    iosBundleId: 'com.example.hustle.RunnerTests',
  );
}
