name: Flutter CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Get all Flutter Packages
      run: cd ./hustle && flutter pub get
    - name: Flutter test
      run: cd ./hustle && flutter test
    - name: Flutter analyze
      run: cd ./hustle && flutter analyze
    - name: Flutter build
      run: cd ./hustle && flutter build apk
